# Generated by Django 4.2.4 on 2023-09-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_snippet_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['name', 'lang']},
        ),
    ]
