# Generated by Django 4.2.4 on 2023-09-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_snippet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
